### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by mlopezantequera**

### CODE REVIEW

**Comment by mlopezantequera** [comment]
@kwotsin, the changes I've made should be compatible with Python 2 as well (I think you can safely merge into master)

**Comment by kwotsin** [comment]
Hmm I think in Python 2 xrange is still way more efficient than range. What do you say?

**Comment by mlopezantequera** [comment]
After importing range from builtins in [line 4 of xception.py](https://github.com/kwotsin/Tensorflow-Xception/blob/python3/xception.py#L4), 'range' will run the python 3 version, also in python 2.

At least according to this [cheatsheet](http://python-future.org/compatible_idioms.html#xrange)

**Comment by kwotsin** [comment]
That's great! I didn't know of that. Is it possible for you to submit another pull request? I'll delete the older branch.

**Pull request merged**
